/**
 * generated by Xtext 2.24.0
 */
package su.nsk.iae.post.poST.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.post.poST.ErrorProcessStatement;
import su.nsk.iae.post.poST.PoSTPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Error Process Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ErrorProcessStatementImpl extends ProcessStatementsImpl implements ErrorProcessStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ErrorProcessStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.ERROR_PROCESS_STATEMENT;
  }

} //ErrorProcessStatementImpl
