/**
 * generated by Xtext 2.23.0
 */
package su.nsk.iae.post.poST.impl;

import org.eclipse.emf.ecore.EClass;

import su.nsk.iae.post.poST.PoSTPackage;
import su.nsk.iae.post.poST.SubprogramControlStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Subprogram Control Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SubprogramControlStatementImpl extends StatementImpl implements SubprogramControlStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubprogramControlStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PoSTPackage.Literals.SUBPROGRAM_CONTROL_STATEMENT;
  }

} //SubprogramControlStatementImpl
