/*
 * generated by Xtext 2.23.0
 */
package su.nsk.iae.post;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PoSTRuntimeModule extends AbstractPoSTRuntimeModule {
}
