/*
 * generated by Xtext 2.23.0
 */
package su.nsk.iae.post.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PoSTUiModule extends AbstractPoSTUiModule {

	public PoSTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
