/*
 * generated by Xtext 2.24.0
 */
package su.nsk.iae.post.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class PoSTWebModule extends AbstractPoSTWebModule {
}
