/**
 * generated by Xtext 2.23.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.CaseElement#getCaseList <em>Case List</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.CaseElement#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getCaseElement()
 * @model
 * @generated
 */
public interface CaseElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Case List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Case List</em>' containment reference.
   * @see #setCaseList(CaseList)
   * @see su.nsk.iae.post.poST.PoSTPackage#getCaseElement_CaseList()
   * @model containment="true"
   * @generated
   */
  CaseList getCaseList();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.CaseElement#getCaseList <em>Case List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Case List</em>' containment reference.
   * @see #getCaseList()
   * @generated
   */
  void setCaseList(CaseList value);

  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference.
   * @see #setStatement(StatementList)
   * @see su.nsk.iae.post.poST.PoSTPackage#getCaseElement_Statement()
   * @model containment="true"
   * @generated
   */
  StatementList getStatement();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.CaseElement#getStatement <em>Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' containment reference.
   * @see #getStatement()
   * @generated
   */
  void setStatement(StatementList value);

} // CaseElement
