/**
 * generated by Xtext 2.24.0
 */
package su.nsk.iae.post.poST;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getName <em>Name</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getFbInVars <em>Fb In Vars</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getFbOutVars <em>Fb Out Vars</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getFbInOutVars <em>Fb In Out Vars</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getFbVars <em>Fb Vars</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getFbTempVars <em>Fb Temp Vars</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getFbExternVars <em>Fb Extern Vars</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.FunctionBlock#getProcesses <em>Processes</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock()
 * @model
 * @generated
 */
public interface FunctionBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.FunctionBlock#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fb In Vars</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.InputVarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fb In Vars</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_FbInVars()
   * @model containment="true"
   * @generated
   */
  EList<InputVarDeclaration> getFbInVars();

  /**
   * Returns the value of the '<em><b>Fb Out Vars</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.OutputVarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fb Out Vars</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_FbOutVars()
   * @model containment="true"
   * @generated
   */
  EList<OutputVarDeclaration> getFbOutVars();

  /**
   * Returns the value of the '<em><b>Fb In Out Vars</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.InputOutputVarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fb In Out Vars</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_FbInOutVars()
   * @model containment="true"
   * @generated
   */
  EList<InputOutputVarDeclaration> getFbInOutVars();

  /**
   * Returns the value of the '<em><b>Fb Vars</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.VarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fb Vars</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_FbVars()
   * @model containment="true"
   * @generated
   */
  EList<VarDeclaration> getFbVars();

  /**
   * Returns the value of the '<em><b>Fb Temp Vars</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.TempVarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fb Temp Vars</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_FbTempVars()
   * @model containment="true"
   * @generated
   */
  EList<TempVarDeclaration> getFbTempVars();

  /**
   * Returns the value of the '<em><b>Fb Extern Vars</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.ExternalVarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fb Extern Vars</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_FbExternVars()
   * @model containment="true"
   * @generated
   */
  EList<ExternalVarDeclaration> getFbExternVars();

  /**
   * Returns the value of the '<em><b>Processes</b></em>' containment reference list.
   * The list contents are of type {@link su.nsk.iae.post.poST.Process}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processes</em>' containment reference list.
   * @see su.nsk.iae.post.poST.PoSTPackage#getFunctionBlock_Processes()
   * @model containment="true"
   * @generated
   */
  EList<su.nsk.iae.post.poST.Process> getProcesses();

} // FunctionBlock
