/**
 * generated by Xtext 2.24.0
 */
package su.nsk.iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Power Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getPowerExpression()
 * @model
 * @generated
 */
public interface PowerExpression extends MulExpression
{
} // PowerExpression
