/**
 * generated by Xtext 2.23.0
 */
package su.nsk.iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link su.nsk.iae.post.poST.RealLiteral#isRSig <em>RSig</em>}</li>
 *   <li>{@link su.nsk.iae.post.poST.RealLiteral#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getRealLiteral()
 * @model
 * @generated
 */
public interface RealLiteral extends NumericLiteral
{
  /**
   * Returns the value of the '<em><b>RSig</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>RSig</em>' attribute.
   * @see #setRSig(boolean)
   * @see su.nsk.iae.post.poST.PoSTPackage#getRealLiteral_RSig()
   * @model
   * @generated
   */
  boolean isRSig();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.RealLiteral#isRSig <em>RSig</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>RSig</em>' attribute.
   * @see #isRSig()
   * @generated
   */
  void setRSig(boolean value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(double)
   * @see su.nsk.iae.post.poST.PoSTPackage#getRealLiteral_Value()
   * @model
   * @generated
   */
  double getValue();

  /**
   * Sets the value of the '{@link su.nsk.iae.post.poST.RealLiteral#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(double value);

} // RealLiteral
