/**
 * generated by Xtext 2.23.0
 */
package su.nsk.iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start Process Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getStartProcessStatement()
 * @model
 * @generated
 */
public interface StartProcessStatement extends ProcessStatements
{
} // StartProcessStatement
