/**
 * generated by Xtext 2.23.0
 */
package su.nsk.iae.post.poST;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see su.nsk.iae.post.poST.PoSTPackage#getUnaryExpression()
 * @model
 * @generated
 */
public interface UnaryExpression extends PowerExpression
{
} // UnaryExpression
